services:
  app:
    image: ${DOCKER_REGISTRY}/yam-offer-view:${DOCKER_BRANCH}
    container_name: ${DOCKER_BRANCH}-yam-offer-view
    environment:
      - COMMUNITY_API_KEY=$COMMUNITY_API_KEY
    networks:
      - traefik-realt
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.yam-offer-view-${DOCKER_BRANCH}.rule=Host(`${HOSTNAME}`)'
      - 'traefik.http.routers.yam-offer-view-${DOCKER_BRANCH}.entrypoints=websecure'
      - 'traefik.http.services.yam-offer-view-${DOCKER_BRANCH}.loadbalancer.server.port=3000'
    restart: always

networks:
  traefik-realt:
    external: true