services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV}
        NEXT_PUBLIC_ETHEREUM_RPC_URL: ${NEXT_PUBLIC_ETHEREUM_RPC_URL}
        NEXT_PUBLIC_GNOSIS_RPC_URL: ${NEXT_PUBLIC_GNOSIS_RPC_URL}
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
    # env_file: ".env"
    environment:
      - COMMUNITY_API_KEY=${COMMUNITY_API_KEY}
      - COMMUNITY_API_URI=${COMMUNITY_API_URI}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
      - NEXT_PUBLIC_ETHEREUM_RPC_URL=${NEXT_PUBLIC_ETHEREUM_RPC_URL}
      - NEXT_PUBLIC_GNOSIS_RPC_URL=${NEXT_PUBLIC_GNOSIS_RPC_URL}
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}

    ports:
      - '3000:3000'